title:              Peel the onions
email:              peeltheonions@gmail.com
description:        Data analytics/data science tutorials and stuff
author:             Sashlin Reddy
baseurl:            ""
url:                "https://peeltheonions.github.io"

# Social Profiles
github_username:    peeltheonions
# facebook_username:  StartBootstrap
instagram_username: sashdowndashreddy
linkedin_username: sashlin-reddy-33b07510b
youtube_username: UCiFvkRyszhn8V0gHSbsFlGA

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-4FWZXLMKX9 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
